tasks:
  build-image:
    type: build
    image: razorops_python
    tags:
      - latest
      - ${CI_COMMIT_SHA:0:8}


workflow:
  - name: production
    tasks: [build-image]
    when: branch == "master"